name: graduation_project2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    
    sdk: flutter
 
  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  youtube_player_iframe: ^4.0.2
  webview_flutter: ^4.4.1
  # Firebase Packages
  firebase_core: ^3.12.1          # Required to initialize Firebase
  firebase_auth: ^5.5.1           # Firebase Authentication

  # State Management (Optional: Choose one if needed)
  provider: ^6.1.0                # For state management (optional)
  flutter_bloc: ^8.1.3            # BLoC pattern (optional)

  # Cloud Firestore (Optional: If you want to use Firestore database)
  cloud_firestore: ^5.0.0

  # Firebase Storage (Optional: For uploading files)
  firebase_storage: ^12.0.0

  # Image Picker (Optional: If you want to allow image selection)
  image_picker: ^1.0.7

  # Video Player (for handling videos)
  video_player: ^2.8.1
  http: ^1.3.0
  youtube_player_flutter: ^9.1.1
  firebase_messaging: ^15.2.4
  
#notifications
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  lottie: ^3.3.1
  intl: ^0.18.1
  flutter_launcher_icons: ^0.14.4
flutter_native_timezone: ^2.0.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_foreground: "assets/images/play_store_512.png"
  adaptive_icon_background: "#ffffff"
  


flutter:
  uses-material-design: true
  assets:
    - assets/animations/Lunge.json
    