// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQ1dtVRN_sXqK-yCGUZaOBVWLselLIjU',
    appId: '1:621264361715:web:8239b818e6dbb11503bf86',
    messagingSenderId: '621264361715',
    projectId: 'graduationproject-3a74a',
    authDomain: 'graduationproject-3a74a.firebaseapp.com',
    storageBucket: 'graduationproject-3a74a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVOquD7KnH5W6_gMiz0ik5F_9HDl43mE',
    appId: '1:621264361715:android:e4022ed09054bcec03bf86',
    messagingSenderId: '621264361715',
    projectId: 'graduationproject-3a74a',
    storageBucket: 'graduationproject-3a74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkznFt5JHWgxbhI3kDW8yR7w37x_mU3xo',
    appId: '1:621264361715:ios:9f06dcb6582e740c03bf86',
    messagingSenderId: '621264361715',
    projectId: 'graduationproject-3a74a',
    storageBucket: 'graduationproject-3a74a.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkznFt5JHWgxbhI3kDW8yR7w37x_mU3xo',
    appId: '1:621264361715:ios:9f06dcb6582e740c03bf86',
    messagingSenderId: '621264361715',
    projectId: 'graduationproject-3a74a',
    storageBucket: 'graduationproject-3a74a.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvQ1dtVRN_sXqK-yCGUZaOBVWLselLIjU',
    appId: '1:621264361715:web:51b6c81202107ca103bf86',
    messagingSenderId: '621264361715',
    projectId: 'graduationproject-3a74a',
    authDomain: 'graduationproject-3a74a.firebaseapp.com',
    storageBucket: 'graduationproject-3a74a.firebasestorage.app',
  );
}